services:
  ui-gallery-vue:
    container_name: ui-gallery-vue
    build:
      context: .
      dockerfile: Dockerfile
      args:
        - NODE_ENV=development
    volumes:
      - .:/var/app:cached
      - ui-gallery-vue-node-modules:/var/app/node_modules
    working_dir: /var/app
    ports:
      - 2222:3000
    tty: true
    environment:
      - NODE_ENV=production
      - CHOKIDAR_USEPOLLING=true # Hot Reload を有効化
      - APP_ENV=local # ビルドしたい環境に合わせ切り替えること(local:ローカル開発、iss:検証環境、prs:本番環境)
    networks:
      - ui-gallery-vue-net
    command: npm run dev

volumes:
  # Volume Trick用の匿名ボリューム
  # node_modulesをホストと切り離すために使用する
  ui-gallery-vue-node-modules:

networks:
  ui-gallery-vue-net:
